-- =====================================================================
-- 15_order.sql  订单域（order_）
-- 域说明：权益订单、场景订单、课程订单、旅居房间订单（统一 ORDER_STATUS 8态）
--         v4.2 调整：order_payment/order_refund 迁入结算域（finance_payment/finance_refund），
--         order_status_log 迁入系统域（system_order_status_log），本域仅保留 4 张业务订单表
-- 表数：4
-- 生成依据：docs/02数据库设计文档_v4.1.md §3.15
-- 主键策略：全部为分片表（雪花ID，应用层 SnowflakeId）
-- =====================================================================

-- ---------------------------------------------------------------------
-- 3.15.1 order_equity 权益订单（分片表，雪花ID）
-- ---------------------------------------------------------------------
DROP TABLE IF EXISTS `order_equity`;
CREATE TABLE `order_equity` (
  `id` BIGINT NOT NULL COMMENT '主键（雪花ID）',
  `order_code` VARCHAR(50) NOT NULL COMMENT '订单编号（OD+年月日+4位序号）',
  `order_source` TINYINT(2) NOT NULL DEFAULT 1 COMMENT '采购来源（1=渠道对公采购, 2=代理人个人采购）',
  `channel_code` VARCHAR(50) DEFAULT NULL COMMENT '渠道编码',
  `channel_full_name` VARCHAR(200) DEFAULT NULL COMMENT '渠道名称（快照）',
  `agent_code` VARCHAR(50) DEFAULT NULL COMMENT '代理人编码',
  `agent_full_name` VARCHAR(50) DEFAULT NULL COMMENT '代理人姓名（快照）',
  `distributor_code` VARCHAR(64) DEFAULT NULL COMMENT '分销商编码（可空）',
  `distributor_full_name` VARCHAR(200) DEFAULT NULL COMMENT '分销商名称（快照）',
  `goods_code` VARCHAR(50) NOT NULL COMMENT '商品编码',
  `goods_name` VARCHAR(200) NOT NULL COMMENT '商品名称',
  `sku_code` VARCHAR(50) NOT NULL COMMENT 'SKU编码',
  `sku_name` VARCHAR(200) NOT NULL COMMENT 'SKU名称',
  `quantity` INT(11) NOT NULL COMMENT '购买数量',
  `unit_price` DECIMAL(12,2) NOT NULL COMMENT '单价',
  `total_amount` DECIMAL(14,2) NOT NULL COMMENT '订单总额',
  `discount_amount` DECIMAL(12,2) NOT NULL DEFAULT 0 COMMENT '优惠金额',
  `pay_amount` DECIMAL(14,2) NOT NULL COMMENT '实付金额',
  `pay_type` TINYINT(2) DEFAULT NULL COMMENT '支付方式（pay_type 字典：1=微信支付, 2=支付宝, 3=银行转账, 4=余额支付, 5=线下支付）',
  `pay_time` DATETIME DEFAULT NULL COMMENT '支付时间',
  `pay_trade_no` VARCHAR(100) DEFAULT NULL COMMENT '支付流水号',
  `deliver_type` TINYINT(2) NOT NULL DEFAULT 1 COMMENT '权益入库方式（1=批量入库, 2=逐张入库, 3=自动入库）',
  `deliver_count` INT(11) NOT NULL DEFAULT 0 COMMENT '已入库数量',
  `deliver_time` DATETIME DEFAULT NULL COMMENT '入库完成时间',
  `expire_time` DATETIME DEFAULT NULL COMMENT '订单过期时间（未支付自动取消）',
  `invoice_status` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '发票状态（0=未申请, 1=已申请, 2=已开具）',
  `organ_code` VARCHAR(50) DEFAULT NULL COMMENT '平台运营方编码',
  `order_status` TINYINT(2) NOT NULL DEFAULT 0 COMMENT '订单状态（0=待支付, 1=已支付, 2=部分发放, 3=已发放, 4=已完成, 5=已取消, 6=退款中, 7=已退款）',
  `cancel_reason` VARCHAR(500) DEFAULT NULL COMMENT '取消原因',
  `remark` VARCHAR(500) DEFAULT NULL COMMENT '备注',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `creator` VARCHAR(64) DEFAULT 'system' COMMENT '创建人',
  `updater` VARCHAR(64) DEFAULT 'system' COMMENT '更新人',
  `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：1已删除/0未删除',
  `deleted_at` DATETIME DEFAULT NULL COMMENT '删除时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_order_code` (`order_code`),
  KEY `idx_channel_code` (`channel_code`),
  KEY `idx_agent_code` (`agent_code`),
  KEY `idx_goods_code` (`goods_code`),
  KEY `idx_order_status` (`order_status`),
  KEY `idx_pay_time` (`pay_time`),
  KEY `idx_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='权益订单';

-- ---------------------------------------------------------------------
-- 3.15.2 order_scene 场景订单（分片表，雪花ID）
-- ---------------------------------------------------------------------
DROP TABLE IF EXISTS `order_scene`;
CREATE TABLE `order_scene` (
  `id` BIGINT NOT NULL COMMENT '主键（雪花ID）',
  `order_code` VARCHAR(50) NOT NULL COMMENT '订单编号',
  `order_type` TINYINT(2) NOT NULL DEFAULT 1 COMMENT '订单类型（1=个人报名, 2=代理人代报, 3=团体报名）',
  `channel_code` VARCHAR(50) DEFAULT NULL COMMENT '渠道编码',
  `channel_full_name` VARCHAR(200) DEFAULT NULL COMMENT '渠道名称（快照）',
  `agent_code` VARCHAR(64) DEFAULT NULL COMMENT '代理人编码',
  `agent_full_name` VARCHAR(50) DEFAULT NULL COMMENT '代理人姓名（快照）',
  `distributor_code` VARCHAR(64) DEFAULT NULL COMMENT '分销商编码（可空）',
  `distributor_full_name` VARCHAR(200) DEFAULT NULL COMMENT '分销商名称（快照）',
  `client_code` VARCHAR(64) NOT NULL COMMENT '客户编码',
  `client_full_name` VARCHAR(50) DEFAULT NULL COMMENT '客户姓名（快照）',
  `goods_code` VARCHAR(50) NOT NULL COMMENT '商品编码',
  `scene_code` VARCHAR(64) NOT NULL COMMENT '场景编码',
  `scene_name` VARCHAR(200) NOT NULL COMMENT '场景名称',
  `sku_code` VARCHAR(64) NOT NULL COMMENT 'SKU 编码',
  `schedule_code` VARCHAR(64) DEFAULT NULL COMMENT '排期编码',
  `activity_date` DATE NOT NULL COMMENT '活动日期',
  `participant_count` INT(11) NOT NULL DEFAULT 1 COMMENT '参与人数',
  `participant_names` TEXT DEFAULT NULL COMMENT '参与人姓名（JSON数组）',
  `unit_price` DECIMAL(12,2) NOT NULL COMMENT '单价',
  `total_amount` DECIMAL(14,2) NOT NULL COMMENT '订单总额',
  `discount_amount` DECIMAL(12,2) NOT NULL DEFAULT 0 COMMENT '优惠金额',
  `pay_amount` DECIMAL(14,2) NOT NULL COMMENT '实付金额',
  `coupon_code` VARCHAR(64) DEFAULT NULL COMMENT '优惠券编码',
  `coupon_amount` DECIMAL(12,2) NOT NULL DEFAULT 0 COMMENT '优惠券抵扣',
  `pay_type` TINYINT(2) DEFAULT NULL COMMENT '支付方式（pay_type 字典：1=微信支付, 2=支付宝, 3=银行转账, 4=余额支付, 5=线下支付）',
  `pay_time` DATETIME DEFAULT NULL COMMENT '支付时间',
  `equity_code` VARCHAR(64) DEFAULT NULL COMMENT '使用的权益编码',
  `contact_name` VARCHAR(50) NOT NULL COMMENT '联系人姓名',
  `contact_phone` VARCHAR(20) NOT NULL COMMENT '联系人电话',
  `remark` VARCHAR(500) DEFAULT NULL COMMENT '备注',
  `order_status` TINYINT(2) NOT NULL DEFAULT 0 COMMENT '状态（0=待支付, 1=已支付, 2=部分发放, 3=已发放, 4=已完成, 5=已取消, 6=退款中, 7=已退款）',
  `cancel_reason` VARCHAR(500) DEFAULT NULL COMMENT '取消原因',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `creator` VARCHAR(64) DEFAULT 'system' COMMENT '创建人',
  `updater` VARCHAR(64) DEFAULT 'system' COMMENT '更新人',
  `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：1已删除/0未删除',
  `deleted_at` DATETIME DEFAULT NULL COMMENT '删除时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_order_code` (`order_code`),
  KEY `idx_scene_code` (`scene_code`),
  KEY `idx_client_code` (`client_code`),
  KEY `idx_agent_code` (`agent_code`),
  KEY `idx_activity_date` (`activity_date`),
  KEY `idx_order_status` (`order_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='场景订单';

-- ---------------------------------------------------------------------
-- 3.15.3 order_course 课程订单（分片表，雪花ID）
-- ---------------------------------------------------------------------
DROP TABLE IF EXISTS `order_course`;
CREATE TABLE `order_course` (
  `id` BIGINT NOT NULL COMMENT '主键（雪花ID）',
  `order_code` VARCHAR(50) NOT NULL COMMENT '订单编号',
  `order_type` TINYINT(2) NOT NULL DEFAULT 1 COMMENT '订单类型（1=自主购买, 2=代理人代报, 3=权益兑换）',
  `channel_code` VARCHAR(50) DEFAULT NULL COMMENT '渠道编码',
  `channel_full_name` VARCHAR(200) DEFAULT NULL COMMENT '渠道名称（快照）',
  `agent_code` VARCHAR(64) DEFAULT NULL COMMENT '代理人编码',
  `agent_full_name` VARCHAR(50) DEFAULT NULL COMMENT '代理人姓名（快照）',
  `distributor_code` VARCHAR(64) DEFAULT NULL COMMENT '分销商编码（可空）',
  `distributor_full_name` VARCHAR(200) DEFAULT NULL COMMENT '分销商名称（快照）',
  `client_code` VARCHAR(64) NOT NULL COMMENT '客户编码',
  `client_full_name` VARCHAR(50) DEFAULT NULL COMMENT '客户姓名（快照）',
  `goods_code` VARCHAR(50) NOT NULL COMMENT '商品编码',
  `course_code` VARCHAR(64) NOT NULL COMMENT '课程编码',
  `course_name` VARCHAR(200) NOT NULL COMMENT '课程名称',
  `sku_code` VARCHAR(64) NOT NULL COMMENT 'SKU 编码',
  `quantity` INT(11) NOT NULL DEFAULT 1 COMMENT '购买数量',
  `unit_price` DECIMAL(12,2) NOT NULL COMMENT '单价',
  `total_amount` DECIMAL(14,2) NOT NULL COMMENT '订单总额',
  `discount_amount` DECIMAL(12,2) NOT NULL DEFAULT 0 COMMENT '优惠金额',
  `pay_amount` DECIMAL(14,2) NOT NULL COMMENT '实付金额',
  `coupon_code` VARCHAR(64) DEFAULT NULL COMMENT '优惠券编码',
  `pay_type` TINYINT(2) DEFAULT NULL COMMENT '支付方式（pay_type 字典：1=微信支付, 2=支付宝, 3=银行转账, 4=余额支付, 5=线下支付）',
  `pay_time` DATETIME DEFAULT NULL COMMENT '支付时间',
  `equity_code` VARCHAR(64) DEFAULT NULL COMMENT '使用的权益编码',
  `order_status` TINYINT(2) NOT NULL DEFAULT 0 COMMENT '状态（0=待支付, 1=已支付, 2=部分发放, 3=已发放, 4=已完成, 5=已取消, 6=退款中, 7=已退款）',
  `cancel_reason` VARCHAR(500) DEFAULT NULL COMMENT '取消原因',
  `remark` VARCHAR(500) DEFAULT NULL COMMENT '备注',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `creator` VARCHAR(64) DEFAULT 'system' COMMENT '创建人',
  `updater` VARCHAR(64) DEFAULT 'system' COMMENT '更新人',
  `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：1已删除/0未删除',
  `deleted_at` DATETIME DEFAULT NULL COMMENT '删除时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_order_code` (`order_code`),
  KEY `idx_course_code` (`course_code`),
  KEY `idx_client_code` (`client_code`),
  KEY `idx_order_status` (`order_status`),
  KEY `idx_channel_code` (`channel_code`),
  KEY `idx_distributor_code` (`distributor_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='课程订单';

-- ---------------------------------------------------------------------
-- 3.15.4 order_sojourn 旅居房间订单（分片表，雪花ID）
-- ---------------------------------------------------------------------
DROP TABLE IF EXISTS `order_sojourn`;
CREATE TABLE `order_sojourn` (
  `id` BIGINT NOT NULL COMMENT '主键（雪花ID）',
  `order_code` VARCHAR(50) NOT NULL COMMENT '订单编号',
  `order_type` TINYINT(2) NOT NULL DEFAULT 1 COMMENT '订单类型（1=自主预订, 2=代理人代订, 3=权益兑换）',
  `channel_code` VARCHAR(50) DEFAULT NULL COMMENT '渠道编码',
  `channel_full_name` VARCHAR(200) DEFAULT NULL COMMENT '渠道名称（快照）',
  `agent_code` VARCHAR(64) DEFAULT NULL COMMENT '代理人编码',
  `agent_full_name` VARCHAR(50) DEFAULT NULL COMMENT '代理人姓名（快照）',
  `distributor_code` VARCHAR(64) DEFAULT NULL COMMENT '分销商编码（可空）',
  `distributor_full_name` VARCHAR(200) DEFAULT NULL COMMENT '分销商名称（快照）',
  `client_code` VARCHAR(64) NOT NULL COMMENT '客户编码',
  `client_full_name` VARCHAR(50) DEFAULT NULL COMMENT '客户姓名（快照）',
  `goods_code` VARCHAR(50) NOT NULL COMMENT '商品编码',
  `park_code` VARCHAR(64) NOT NULL COMMENT '机构编码',
  `park_full_name` VARCHAR(200) NOT NULL COMMENT '机构名称（快照）',
  `room_type_code` VARCHAR(64) NOT NULL COMMENT '房间类型编码',
  `sku_code` VARCHAR(64) NOT NULL COMMENT 'SKU 编码',
  `checkin_date` DATE NOT NULL COMMENT '入住日期',
  `checkout_date` DATE NOT NULL COMMENT '退房日期',
  `stay_days` INT(11) NOT NULL COMMENT '入住天数',
  `resident_count` INT(11) NOT NULL DEFAULT 1 COMMENT '入住人数',
  `resident_names` TEXT DEFAULT NULL COMMENT '入住人姓名（JSON数组）',
  `care_type_code` VARCHAR(64) DEFAULT NULL COMMENT '照护类型编码',
  `food_type_code` VARCHAR(64) DEFAULT NULL COMMENT '餐饮类型编码',
  `room_fee` DECIMAL(12,2) NOT NULL COMMENT '房间费用',
  `care_fee` DECIMAL(12,2) NOT NULL DEFAULT 0 COMMENT '照护费用',
  `food_fee` DECIMAL(12,2) NOT NULL DEFAULT 0 COMMENT '餐饮费用',
  `other_fee` DECIMAL(12,2) NOT NULL DEFAULT 0 COMMENT '其他费用',
  `total_amount` DECIMAL(14,2) NOT NULL COMMENT '订单总额',
  `discount_amount` DECIMAL(12,2) NOT NULL DEFAULT 0 COMMENT '优惠金额',
  `pay_amount` DECIMAL(14,2) NOT NULL COMMENT '实付金额',
  `coupon_code` VARCHAR(64) DEFAULT NULL COMMENT '优惠券编码',
  `pay_type` TINYINT(2) DEFAULT NULL COMMENT '支付方式（pay_type 字典：1=微信支付, 2=支付宝, 3=银行转账, 4=余额支付, 5=线下支付）',
  `pay_time` DATETIME DEFAULT NULL COMMENT '支付时间',
  `deposit_amount` DECIMAL(12,2) DEFAULT NULL COMMENT '押金金额',
  `equity_code` VARCHAR(64) DEFAULT NULL COMMENT '使用的权益编码',
  `contact_name` VARCHAR(50) NOT NULL COMMENT '联系人姓名',
  `contact_phone` VARCHAR(20) NOT NULL COMMENT '联系人电话',
  `special_needs` TEXT DEFAULT NULL COMMENT '特殊需求',
  `order_status` TINYINT(2) NOT NULL DEFAULT 0 COMMENT '状态（0=待支付, 1=已支付, 2=部分发放, 3=已发放, 4=已完成, 5=已取消, 6=退款中, 7=已退款）',
  `cancel_reason` VARCHAR(500) DEFAULT NULL COMMENT '取消原因',
  `remark` VARCHAR(500) DEFAULT NULL COMMENT '备注',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `creator` VARCHAR(64) DEFAULT 'system' COMMENT '创建人',
  `updater` VARCHAR(64) DEFAULT 'system' COMMENT '更新人',
  `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：1已删除/0未删除',
  `deleted_at` DATETIME DEFAULT NULL COMMENT '删除时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_order_code` (`order_code`),
  KEY `idx_park_code` (`park_code`),
  KEY `idx_client_code` (`client_code`),
  KEY `idx_checkin_date` (`checkin_date`),
  KEY `idx_order_status` (`order_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='旅居房间订单';
